# @name login
POST http://localhost:8086/api/v2/signin HTTP/1.1
Authorization: Basic user:password

@authToken = naPOjupdqF8q-WAb_EXTzxXqI0DxA4j05N5XtvJG6vxtr3bg8VTX-ffa69ekbPgL5xPnl6Xe9nx4_0Yrafi1Bw==

###

# @name write
POST http://localhost:8086/api/v2/write?org=org&bucket=default&precision=ns
Authorization: Basic ros:rosinflux

test,sensor=test value=0.352484

###

# @name read
POST http://localhost:8086/api/v2/query?org=rosinflux&bucket=datalog
Authorization: Token QDBCYCGPiP982ff7WS98jRMTciLof4pDTdkV3O_Z7iltf8z9_t5TWeREKNHnTw-uXD0WeXwdikLqvuXDyjHQHA==

{
    "query": "mem"
}