[package]
name = "rosbridge"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.115"
serde_json = { version = "1.0.78", features = ["raw_value"] }

strum = "0.23"
strum_macros = "0.23"
