[data_logging]
    [data_logging.low_speed]
        sample_period = 20 # ms
        logging_period = 1000 # ms

    [data_logging.high_speed]
        sample_period = 1 # ms

[i2c]
    bus = "/dev/i2c-1"
    [i2c.ads1014.p_h2o2]
        address = "0x48"
        conf0 = "0b10000000"
        conf1 = "0b10000011"

    [i2c.ads1014.loadcell]
        address = "0x49"
        conf0 = "0b10000000"
        conf1 = "0b10000011"

    [i2c.ads1014.p_chamber]
        address = "0x4A"
        conf0 = "0b10000000"
        conf1 = "0b10000011"

    [i2c.ads1014.t_chamber]
        address = "0x4B"
        conf0 = "0b10001010"
        conf1 = "0b10000011"

[pressureControl]
    pressureSetPoint = 20 #bar
    pressureControlPeriod = 5 #ms
