# https://www.beyondlogic.org/an-introduction-to-chardev-gpio-and-libgpiod-on-the-raspberry-pi/
# https://embeddedbits.org/new-linux-kernel-gpio-user-space-interface/

[gpio]
    [gpio.valveBV]
    chipNumber = 0
    lineNumber = 21
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valvePV]
    chipNumber = 0
    lineNumber = 26
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valveMV1]
    chipNumber = 0
    lineNumber = 20
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valveMV2]
    chipNumber = 0
    lineNumber = 19
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.pyro]
    chipNumber = 0
    lineNumber = 16
    sim = false
    mode = "output"
    defaultLevel = 0
