# https://www.beyondlogic.org/an-introduction-to-chardev-gpio-and-libgpiod-on-the-raspberry-pi/
# https://embeddedbits.org/new-linux-kernel-gpio-user-space-interface/

[data_logging]
    [data_logging.low_speed]
        sample_period = 20 # ms
        logging_period = 1000 # ms

    [data_logging.high_speed]
        sample_period = 1 # ms

[ignition_sequence]
    [ignition_sequence.BV]
    open = -1 # Not actuated
    close = -1 # Not actuated

    [ignition_sequence.PV]
    open = -1 # ms
    close = -1 # ms

    [ignition_sequence.MV1]
    open = 0 # ms
    close = 1000 # ms

    [ignition_sequence.MV2]
    open = -1 # ms
    close = -1 # ms

    [ignition_sequence.Purge]
    open = 1100 # ms
    close = 2000 # ms

    [ignition_sequence.ignitor]
    on = -1 # ms
    off = -1 # ms

    [ignition_sequence.high_speed_data_logging]
    on = 0 # ms
    off = 2100 # ms

    [ignition_sequence.end]
    end = 2500 # ms

[gpio]
    [gpio.valveBV]
    chipNumber = 0
    lineNumber = 27
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valvePV]
    chipNumber = 0
    lineNumber = 22
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valveMV1]
    chipNumber = 0
    lineNumber = 23
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valveMV2]
    chipNumber = 0
    lineNumber = 24
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.valvePurge]
    chipNumber = 0
    lineNumber = 25
    sim = false
    mode = "output"
    defaultLevel = 0

    [gpio.pyro]
    chipNumber = 0
    lineNumber = 17
    sim = false
    mode = "output"
    defaultLevel = 0
