# https://www.beyondlogic.org/an-introduction-to-chardev-gpio-and-libgpiod-on-the-raspberry-pi/
# https://embeddedbits.org/new-linux-kernel-gpio-user-space-interface/

[sense]
chipNumber = 0
lineNumber = 16
sim = true
mode = "input"

[pyro]
chipNumber = 0
lineNumber = 19
sim = true
mode = "output"
