name: Build and publish CI Docker image

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:
    docker_build_publish:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker
              run: |
                docker build . -f .testcontainer/Dockerfile -t testcontainer
                docker save testcontainer:latest | gzip > testcontainer.tar.gz

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    testcontainer.tar.gz
