name: Build and Publish Release

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:
    docker_build_publish:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build
              run: |
                source /opt/ros/galactic/setup.bash
                colcon build --cmake-args '-DCMAKE_BUILD_TYPE=Release'
                tar -czvf rocketdata.tar.gz install

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    rocketdata.tar.gz
