name: Build and publish CI Docker image

# Trigger on changes to dependacies (CMake), Dockerfile definition or 
# GitHub Actions on main branch or manually
on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    docker_build_publish:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.CR_PAT }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                    file: ./.testcontainer/Dockerfile
                    platforms: linux/arm64
                    push: true
                    tags: ghcr.io/tnagyzambo/rocketdata/testcontainer:${{ env.RELEASE_VERSION }}
